# Generated by Django 4.1.5 on 2023-03-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_alter_emailconfiguration_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
