# Generated by Django 4.1.5 on 2023-03-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_sentemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentemail',
            old_name='email_body',
            new_name='body',
        ),
    ]
