# Generated by Django 4.1.5 on 2023-05-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_rename_email_body_sentemail_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='receiver',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
