# Generated by Django 4.1.5 on 2023-02-26 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
    ]
