# Generated by Django 4.1.5 on 2023-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
