# Generated by Django 4.1.5 on 2023-03-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=100)),
                ('l_name', models.CharField(blank=True, max_length=100)),
                ('facility', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('fa_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('n_facility', models.IntegerField(blank=True, null=True)),
                ('date_hosipitalized', models.DateField(blank=True, null=True)),
                ('equip', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Telehealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=100)),
                ('l_name', models.CharField(blank=True, max_length=100)),
                ('facility', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('n_facility', models.IntegerField(blank=True, null=True)),
                ('date_hosipitalized', models.DateField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=100)),
                ('l_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('facility', models.CharField(blank=True, max_length=100)),
                ('date_hosipitalized', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='apply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='equip',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='owner',
        ),
        migrations.AddField(
            model_name='apply',
            name='bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='date_hosipitalized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='n_facility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apply',
            name='p_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
