# Generated by Django 4.1.5 on 2023-09-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_notification_to_admin_alter_notification_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='facility_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
