# Generated by Django 4.1.5 on 2023-03-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_equip_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='telehealth',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
