# Generated by Django 4.1.5 on 2023-03-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_telehealth_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('f_name', models.CharField(blank=True, max_length=100)),
                ('l_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('core', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
