# Generated by Django 4.1.5 on 2023-03-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_firstaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apply',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equip',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firstaid',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telehealth',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topbutton',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
