# Generated by Django 4.1.5 on 2023-03-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_analytic_read_apply_read_book_read_equip_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='equip',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='firstaid',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='telehealth',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='topbutton',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
