# Generated by Django 4.1.5 on 2023-04-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_analytic_created_on_apply_created_on_book_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstaid',
            old_name='name',
            new_name='org_name',
        ),
    ]
