# Generated by Django 4.1.5 on 2023-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_name_firstaid_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaid',
            name='no_of_employees',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='firstaid',
            name='core',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
