# Generated by Django 4.1.5 on 2023-05-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_demorequest_delete_topbutton_alter_firstaid_f_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='n_facility',
            new_name='facility_phone_number',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='p_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='p_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='demorequest',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='demorequest',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='equip',
            old_name='f_name',
            new_name='facility_name',
        ),
        migrations.RenameField(
            model_name='equip',
            old_name='n_facility',
            new_name='facility_phone_number',
        ),
        migrations.RenameField(
            model_name='equip',
            old_name='fa_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='equip',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='firstaid',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='firstaid',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='telehealth',
            old_name='n_facility',
            new_name='facility_phone_number',
        ),
        migrations.RenameField(
            model_name='telehealth',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='telehealth',
            old_name='l_name',
            new_name='last_name',
        )
    ]
