# Generated by Django 4.1.5 on 2023-05-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_n_facility_apply_facility_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demorequest',
            name='date_hosipitalized',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='date_hosipitalized',
        ),
        migrations.RemoveField(
            model_name='telehealth',
            name='date_hosipitalized',
        ),
    ]
