# Generated by Django 4.1.5 on 2023-07-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Encounter',
            new_name='DoctorNote',
        ),
    ]
