# Generated by Django 4.1.5 on 2023-07-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_appointmenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='time',
            field=models.TimeField(unique=True),
        ),
    ]
