# Generated by Django 4.1.5 on 2023-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_appointmenttime_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
