# Generated by Django 4.1.5 on 2023-07-11 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_appointmentduration_appointmenttime_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.appointmentduration'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.appointmenttime'),
        ),
    ]
