# Generated by Django 4.1.5 on 2023-07-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_appointment_duration_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilitySpeciality',
            new_name='Speciality',
        ),
        migrations.RenameModel(
            old_name='SpecialityField',
            new_name='ProviderCategory',
        ),
    ]
