# Generated by Django 4.1.5 on 2023-07-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_rename_facilityspeciality_providercategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default='', max_length=10),
        ),
    ]
