# Generated by Django 4.1.5 on 2023-07-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
