# Generated by Django 4.1.5 on 2023-07-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_alter_appointmentduration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornote',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.appointment'),
        ),
    ]
