# Generated by Django 4.1.5 on 2023-08-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_cervicalcytology_cervicalcytologysite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationRequestedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='examinationrequested',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations_requested', to='facilities.examinationrequestedgroup'),
        ),
    ]
