# Generated by Django 4.1.5 on 2023-08-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0014_examinationrequestedgroup_examinationrequested_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionTerminology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctornote',
            name='date',
        ),
        migrations.RemoveField(
            model_name='doctornote',
            name='description',
        ),
        migrations.AddField(
            model_name='doctornote',
            name='attended_treatment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='next_treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='progress_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='treatment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='examination_requested',
            field=models.ManyToManyField(blank=True, to='facilities.examinationrequested'),
        ),
    ]
