# Generated by Django 4.1.5 on 2023-08-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0015_clientbehavior_interventionterminology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner_comment', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.appointment')),
                ('client_behavior', models.ManyToManyField(to='facilities.clientbehavior')),
                ('intervention_terminologies', models.ManyToManyField(to='facilities.interventionterminology')),
            ],
        ),
    ]
