# Generated by Django 4.1.5 on 2023-08-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0016_mentalform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestrequest',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='last_dose_date',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='last_dose_time',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='sample_date',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='sample_time',
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.appointment'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='last_dose_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sample_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
