# Generated by Django 4.1.5 on 2023-08-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0017_remove_labtestrequest_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestrequest',
            name='cervical_cytology_site',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='sample_type',
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='cervical_cytology_site',
            field=models.ManyToManyField(blank=True, to='facilities.cervicalcytologysite'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sample_type',
            field=models.ManyToManyField(blank=True, to='facilities.sampletype'),
        ),
    ]
