# Generated by Django 4.1.5 on 2023-08-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0018_remove_labtestrequest_cervical_cytology_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='zoom_meeting_creation_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
