# Generated by Django 4.1.5 on 2023-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0020_remove_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='recommendation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.TextField(null=True),
        ),
    ]
