# Generated by Django 4.1.5 on 2023-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0022_appointment_consultation_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mentalform',
            name='access_to_gun',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='additional_substance_use_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='aspects_of_health',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='counselling_experience',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='current_health',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='currently_experiencing_suicidal_thoughts',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='currently_having_mental_health_provider',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='currently_taking_prescriptions',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='emergency_contact_email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='emergency_contact_phone_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='ever_attempted_suicide',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='ever_been_hospitalized',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='ever_been_in_counselling',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='ever_diagnosed_with_mental_illness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='family_receiving_counselling_from_us',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='first_born_ro_last_born',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='hospitalized_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='how_many_in_family',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='mental_health_provider_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='mental_illness_diagnosed_with',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='on_site_counselling',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='prescription_dosage_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='referrer_source',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='suicide_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='supportive_people',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='time_lived_in_current_place',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='want_counselling_or_someone_else_told_you_to',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='who_brought_you_into_counselling',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='who_is_getting_counselling',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='why_seek_counselling',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='counselling_related_topics',
            field=models.ManyToManyField(blank=True, to='facilities.counsellingtopic'),
        ),
    ]
