# Generated by Django 4.1.5 on 2023-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0023_counsellingexperience_counsellingtopic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20)),
            ],
        ),
    ]
