# Generated by Django 4.1.5 on 2023-08-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0027_substance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_of_use', models.CharField(blank=True, max_length=40, null=True)),
                ('amount_typically_used', models.CharField(blank=True, max_length=40, null=True)),
                ('age_of_first_use', models.IntegerField(blank=True, null=True)),
                ('age_of_last_use', models.IntegerField(blank=True, null=True)),
                ('used_in_last_48_hrs', models.CharField(blank=True, max_length=10, null=True)),
                ('used_in_last_30_days', models.CharField(blank=True, max_length=10, null=True)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.substance')),
            ],
        ),
    ]
