# Generated by Django 4.1.5 on 2023-02-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0028_alter_encounter_doctor_alter_encounter_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityspeciality',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
