# Generated by Django 4.1.5 on 2023-08-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0029_substanceusage_mental_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substanceusetitle',
            name='form_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
