# Generated by Django 4.1.5 on 2023-02-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0029_facilityspeciality_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='county',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
