# Generated by Django 4.1.5 on 2023-02-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0030_condition_slug_constituency_slug_county_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
