# Generated by Django 4.1.5 on 2023-08-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0031_mentalform_selected_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalform',
            name='send_email',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='send_text_message',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='send_whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
