# Generated by Django 4.1.5 on 2023-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_reply_blog'),
        ('facilities', '0031_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.tag'),
        ),
    ]
