# Generated by Django 4.1.5 on 2023-02-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0032_service_long_description_service_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='services/images/'),
        ),
    ]
