# Generated by Django 4.1.5 on 2023-08-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0032_mentalform_send_email_mentalform_send_text_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalform',
            name='can_be_in_any_of_cities',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='residing_in_cities',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
