# Generated by Django 4.1.5 on 2023-02-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0033_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
