# Generated by Django 4.1.5 on 2023-08-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0034_mentalform_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='substanceusetitle',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
