# Generated by Django 4.1.5 on 2023-02-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0034_alter_service_charges_alter_service_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='description',
            new_name='about',
        ),
    ]
