# Generated by Django 4.1.5 on 2023-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0035_substanceusetitle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='substanceusetitle',
            name='placeholder',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
