# Generated by Django 4.1.5 on 2023-02-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0035_rename_description_doctor_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_kind',
            field=models.CharField(blank=True, choices=[('pharmacy', 'Pharmacy'), ('clinic', 'Clinic'), ('nutraceutical', 'Nutraceuticals')], max_length=100, null=True),
        ),
    ]
