# Generated by Django 4.1.5 on 2023-02-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0036_alter_facility_facility_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='shared_encounters',
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('prescription', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='facilities.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='facilities.patient')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='shared_prescriptions',
            field=models.ManyToManyField(blank=True, related_name='shared_encounters', to='facilities.prescription'),
        ),
    ]
