# Generated by Django 4.1.5 on 2023-08-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0038_remove_mentalform_counselling_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalform',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalform',
            name='family_counselling_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
