# Generated by Django 4.1.5 on 2023-03-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0039_alter_facility_facility_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility'),
        ),
    ]
