# Generated by Django 4.1.5 on 2023-08-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0040_teletherapyservice_mentalform_services_wanted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='zoom_meeting_creation_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
