# Generated by Django 4.1.5 on 2023-03-03 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0041_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.prescription')),
            ],
        ),
    ]
