# Generated by Django 4.1.5 on 2023-08-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0041_alter_appointment_zoom_meeting_creation_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(null=True),
        ),
    ]
