# Generated by Django 4.1.5 on 2023-03-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0042_sharedprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='doctors/files/'),
        ),
    ]
