# Generated by Django 4.1.5 on 2023-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0045_alter_patient_blood_group_alter_qualification_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityspeciality',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
