# Generated by Django 4.1.5 on 2023-03-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0048_qualificationcourse_specialityfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_file',
            field=models.FileField(null=True, upload_to='providers/files/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='regulatory_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.specialityfield'),
        ),
    ]
