# Generated by Django 4.1.5 on 2023-03-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0049_doctor_license_file_doctor_regulatory_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.qualificationcourse'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='file',
            field=models.FileField(null=True, upload_to='doctors/files/'),
        ),
    ]
