# Generated by Django 4.1.5 on 2023-03-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0050_alter_qualification_course_alter_qualification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(max_length=100),
        ),
    ]
