# Generated by Django 4.1.5 on 2023-03-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0051_alter_qualification_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
