# Generated by Django 4.1.5 on 2023-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0052_alter_qualification_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reson_for_signup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
