# Generated by Django 4.1.5 on 2023-03-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0053_patient_reson_for_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='reson_for_signup',
            new_name='reason_for_signup',
        ),
    ]
