# Generated by Django 4.1.5 on 2023-03-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0054_rename_reson_for_signup_patient_reason_for_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
