# Generated by Django 4.1.5 on 2023-03-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0056_alter_servicecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.illness'),
        ),
    ]
