# Generated by Django 4.1.5 on 2023-05-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0057_alter_appointment_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='other_condition',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
