# Generated by Django 4.1.5 on 2023-05-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0059_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
