# Generated by Django 4.1.5 on 2023-07-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='appointment_video_link_update_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_video_link_update_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='appointment_video_link_update_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_video_link_update_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='patient_appointment_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointment_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='patient_appointment_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointment_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
    ]
