# Generated by Django 4.1.5 on 2023-02-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_emailconfiguration_email_and_more'),
        ('mainapp', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='doctor_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='doctor_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='patient_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='patient_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='prescription_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='prescription_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
    ]
