# Generated by Django 4.1.5 on 2023-02-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_emailconfiguration_email_and_more'),
        ('mainapp', '0010_appconfig_doctor_creation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='facility_authorized_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_authorized_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='facility_authorized_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_authorized_emailconfig', to='mailer.emailconfiguration'),
        ),
    ]
