# Generated by Django 4.1.5 on 2023-03-03 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_emailconfiguration_email_and_more'),
        ('mainapp', '0011_appconfig_facility_authorized_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='appointment_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='appointment_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='prescription_quotation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_quotation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='prescription_quotation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_quotation_emailconfig', to='mailer.emailconfiguration'),
        ),
    ]
