# Generated by Django 4.1.5 on 2023-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_appconfig_appointment_creation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
