# Generated by Django 4.1.5 on 2023-03-15 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_rename_email_body_sentemail_body'),
        ('mainapp', '0015_blog_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='listing_activated',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='contact_form_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='contact_form_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form_emailconfig', to='mailer.emailconfiguration'),
        ),
    ]
