# Generated by Django 4.1.5 on 2023-03-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_rename_email_body_sentemail_body'),
        ('mainapp', '0016_remove_appconfig_listing_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='doctor_authorized_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_authorized_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='doctor_authorized_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_authorized_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='facility_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='facility_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
    ]
