# Generated by Django 4.1.5 on 2023-05-09 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_rename_email_body_sentemail_body'),
        ('mainapp', '0017_appconfig_doctor_authorized_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='analytic_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytic_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='analytic_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytic_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='apply_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='apply_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='book_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='book_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='demorequest_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demorequest_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='demorequest_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demorequest_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='equip_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equip_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='equip_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equip_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='firstaid_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstaid_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='firstaid_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstaid_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='schedule_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='schedule_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='telehealth_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telehealth_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='telehealth_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telehealth_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
    ]
