# Generated by Django 4.1.5 on 2023-06-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('pharma_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('licence', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('alternative_email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('alternative_number', models.IntegerField(blank=True, null=True)),
                ('date_created', models.TextField(blank=True)),
                ('attach', models.ImageField(blank=True, null=True, upload_to='media/pharmacy')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
