# Generated by Django 4.1.5 on 2023-02-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0019_product_delivered_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
