# Generated by Django 4.1.5 on 2023-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_code',
            new_name='trans_ref',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='other_payment_information',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='other_transaction_information',
        ),
        migrations.AddField(
            model_name='payment',
            name='other_payment_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='other_trans_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='trans_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='trans_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
