# Generated by Django 4.1.5 on 2023-02-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_reply_blog'),
        ('shop', '0008_producttype_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.tag'),
        ),
    ]
