# Generated by Django 4.1.5 on 2023-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_transaction_code_payment_trans_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='other_payment_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='other_trans_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
