# Generated by Django 4.1.5 on 2023-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_payment_other_payment_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.FloatField(default=0.0),
        ),
    ]
