# Generated by Django 4.1.5 on 2023-02-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_prescriptionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionorder',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered')], default='confirmed', max_length=30),
        ),
    ]
