# Generated by Django 4.1.5 on 2023-02-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_prescriptionorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionorder',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionorder',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered')], default='new', max_length=30, null=True),
        ),
    ]
