# Generated by Django 4.1.5 on 2023-03-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionorder',
            name='amount',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
