# Generated by Django 4.1.5 on 2023-03-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_prescriptionorder_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
