# Generated by Django 4.1.5 on 2023-03-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_prescriptionorder_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
