# Generated by Django 4.1.5 on 2023-02-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
